import { Hero } from "@/components";
import CategoryList, { Category } from "@/components/category-list";
import { getCategories } from "@/lib/data";
import { GetServerSideProps } from "next";
import Head from "next/head";

interface HomeProps {
  categories: Category[];
}

export default function Home(props: HomeProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero />
      <section className='sec-with-padding'>
        <h2 className='centered '>Exclusive Products</h2>
        <CategoryList categories={props.categories} />
      </section>
      <section className='sec-with-padding'>
        <h2 className='centered '>Available Categories</h2>
        <CategoryList categories={props.categories} />
      </section>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  const categories = await getCategories();
  return {
    props: {
      categories,
    },
  };
};
